#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 STRONG put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 3000 STRONG put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 5000 STRONG put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 10000 STRONG put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 STRONG put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 STRONG get round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 3000 STRONG get round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 5000 STRONG get round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 10000 STRONG get round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 EVENTUAL get round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 3000 EVENTUAL get round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 5000 EVENTUAL get round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 10000 EVENTUAL get round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 EVENTUAL get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 3000 EVENTUAL get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 5000 EVENTUAL get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 10000 EVENTUAL get_put round_robin
java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 EVENTUAL get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 STRONG get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 3000 STRONG get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 5000 STRONG get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 10000 STRONG get_put round_robin
java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 STRONG get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 MONOTONIC_READS get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 3000 MONOTONIC_READS get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 5000 MONOTONIC_READS get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 10000 MONOTONIC_READS get_put round_robin
java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 MONOTONIC_READS get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 READ_MY_WRITES get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 3000 READ_MY_WRITES get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 5000 READ_MY_WRITES get_put round_robin
#java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 10000 READ_MY_WRITES get_put round_robin
java -cp ./target/ReplicatedDatabase-1.0-SNAPSHOT.jar com.kv.service.grpc.LevelDBNormalClient 1000 READ_MY_WRITES get_put round_robin